[workspace]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "ml-odyssey"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
mojo = ">=0.25.7.0.dev2025110405,<0.26"
pre-commit = ">=3.5.0"
prettytable = ">=3.17.0,<4"
pygithub = ">=2.8.1,<3"
